### ISSUE TITLE
US-10: Classroom location from Google Calendar

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#10]
As a user, I want the application to detect the next class's location in the Google Calendar.

**Associated epic:** #19 

**Associated tasks:**
- [x] User is able to log into their Google account through the application
- [x] User should be able to choose multiple calendars to sync 
- [x] Load events from calendar into application
- [ ] Classroom location from next calendar event is loaded as the destination

**Acceptance criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | User selects a calendar event | The classroom associated with the event is loaded as the search destination |

Mockup:
![image](https://user-images.githubusercontent.com/40539079/74111247-61074a00-4b61-11ea-9c50-a239fe44d379.png)
