### ISSUE TITLE
US-11: Find classroom in specific floor

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#11]
As a user, I want to be able to find my classroom on a specific floor in the shortest distance possible.
This user story deals with classrooms only within the same floor. This will mainly be done by creating ionic providers.

Associated epic:
#20 

Associated tasks:
- [x] use SVG.js to retrieve data from an svg file or the DOM in order to search for a classroom by it's id in the DOM.
- [x] create the A* Algorithm that will output the shortest path between nodes.
- [x] create a way to display the path on the floorplan.

**Comment by samiha-rahman** [comment]
Reopening since product owner has not signed off on acceptance criteria yet

**Comment by mosaliza** [comment]
- Should be able to explore the floor

**Comment by samiha-rahman** [comment]
> * Should be able to explore the floor

Added to acceptance critera

**Comment by samiha-rahman** [comment]
Navigating the indoor floorplan is dealt with in #129
