### ISSUE TITLE
Write end to end tests for indoor navigation

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/soen390#114]
As a developer, I need to have a sufficient number of cases covered by system tests for the indoor navigation aspect of the application

**Associated epic:** #35 

**Tasks:**
- [x] Start and end location on same floor
- [x] Start and end location on different floors 
- [ ] Start location indoor and end location outdoor 
- [ ] Start location in Hall building and end location in Loyola building
