### ISSUE TITLE
US-67: Adapt Queued Routes

### ISSUE THREAD

**Issue by a-paggabao** [samiha-rahman/soen390#138]
As a user, I would like to see all selected events that can be migrated as a route so that I can manage them efficiently.

- User should be able to create, edit and delete a queued route
- User should be able to synchronize eligible events from Google Calendar into the queued routes

**Tasks:**

- [ ] Create _Caching_ for queued routes (shareReplay from RxJS or Sqlite)
- [ ] Add a queue for future routes (and events from user's google calendar)
- [ ] Create service for Firestore
- [ ] Add dummy POIs in Firestore for testing

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | ? | ? | 
... | ... | ... | 

**Mockups:**

 ![image.png](https://images.zenhubusercontent.com/5e2b220c4e4265a441e22598/3ad22930-1b64-42fe-bdec-7691590e94c2)

**Comment by david0455** [comment]
no longer implementing
