### ISSUE TITLE
US-14: Find classrooms between different floors

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#14]
As a user, I would like to be able to find my classroom on a different floor in the shortest distance possible.

Associated epic:
#20 

**Tasks:**
- [x] Add the option to select the mode of vertical transportation
- [x] Display the first part of the path
- [x] On button click, display the second part of the path

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Input starting location and destination | The path from starting to destination point should be displayed | 
2 | Select vertical transportation option | The previous option should be deselected and the path generated should use the specified method of transportation | 

Mockup:
![image](https://user-images.githubusercontent.com/40539079/74111340-fc98ba80-4b61-11ea-939e-bc17830dfd0d.png)

**Comment by samiha-rahman** [comment]
Reopening since product owner has not signed off on acceptance criteria yet
