### ISSUE TITLE
US-16: Direction to the nearest outdoor point of interest

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#16]
As a user, I want to have the directions on the map to the selected point of interest.

**Associated epic:** #21 

**Tasks:**
- [x] User can choose either current location or select a location as starting point
- [x] Route to selected point of interest is generated 
- [x] Route is displayed on the outdoor map 

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Select an outdoor point of interest | Application should display option "Get directions to here" | Passed
2 | Ask for directions to selected point of interest | Route is generated and displayed to the user | Passed
