### ISSUE TITLE
US-25: Display indoor map

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#31]
As a user, I would like to see the indoor map of the building I am at. 
This user story will allow the indoor map to be displayed on the users screen.

Associated epic:
#20

Associated tasks:
- [x] create the SVG for a floor plan (in illustrator)
- [x] create a component that will allow the floorplan to be displayed (eg. <floor-plan building="b" floor="f"></floor-plan>)
- [x] create a provider that will use SVG.js library to manipulate the DOM and retrieve/add SVG elements

Mockup:
![image](https://user-images.githubusercontent.com/40539079/74111154-7039c800-4b60-11ea-9245-02b9b705d259.png)

**Comment by samiha-rahman** [comment]
Reopening since product owner has not signed off on acceptance criteria yet

**Comment by mosaliza** [comment]
- Should be able to zoom-in/zoom-out
- Room numbers for classrooms should be added 
- Clicking on a room allows option to select as starting point or end destination 
- Display different floor levels (side bar to select floor number)

**Comment by samiha-rahman** [comment]
> * Should be able to zoom-in/zoom-out
> * Room numbers for classrooms should be added
> * Clicking on a room allows option to select as starting point or end destination
> * Display different floor levels (side bar to select floor number)

Added to acceptance criteria
