### ISSUE TITLE
US-4:  Pop-up additional building information

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#4]
As a user, I want to know more information about the campus buildings.

**Associated epic:** #17 

**Associated tasks:**
- [ ] Clicking on a Concordia building triggers a slide-up window 
- [ ] Accurate details pertaining to selected building are displayed
- [ ] Include a button to view the indoor map of the selected building (i.e. Hall Building) 

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Click on Concordia building on the outdoor map | Information about the selected building is displayed in a slide-up window | 
2 | Click on indoor map view | Indoor map view of the Hall Building is displayed |
3 | View additional building information | Building hours, address, indoor POI, indoor map access are displayed |
4 | Select indoor map option | Indoor map of the designated building is displayed |

**Mockups:**
![image](https://user-images.githubusercontent.com/40539079/74111195-db839a00-4b60-11ea-9e32-069ffc1fde67.png)
![image](https://user-images.githubusercontent.com/40539079/74111197-dfafb780-4b60-11ea-9539-538feff691c8.png)
