### ISSUE TITLE
US-30: Update software architecture

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#40]
As a developer, I need to update the software architecture of the system.

- [x] Update [Overall Diagram](https://www.lucidchart.com/invitations/accept/2e054857-e8b0-418f-91d6-8d5c37be4346) Refine the resources needed for the core features.

- [x] Update [Component Diagram](https://www.lucidchart.com/invitations/accept/18d91b78-c50c-4f10-848f-f81f846f04c9) Refine the components per discussed from Overall Structure.

- [x] Update [Class Diagram](https://www.lucidchart.com/invitations/accept/b8e60e18-bd16-4e0b-b55e-2ad2a04d555d) Modify Domain Diagram to represent standard Domain Diagram (remove methods). Refine Class Diagram to convey the design discussed with the team.
