### ISSUE TITLE
US-38: Travis-CI integration

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/soen390#54]
As a developer, I'd like to have a CI/CD pipeline set up to automatically run tests on every build. 

Associated epic: #35 

Tasks: 
- [x] Link Travis-CI to repo 
- [x] Install desired browser on Travis-CI virtual machine 
- [x] Automatically trigger builds on each commit and run tests
