### ISSUE TITLE
US-6: Current building as starting point

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#6]
As a user, I want to have the building I am currently located in selected as start destination.

**Associated epic:** #18

**Associated tasks:**
- [x] Geolocation is able to detect which building you are located in 
- [x] Display to the user which building they are located in 
- [ ] Be able to select current building as the starting point

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Be located in one of Concordia's building and launch the application | Application should display which building the user is currently located in | 
2 | Select current building as the starting point | Starting point should be populated with the address of the current building the user is located in |

**Comment by david0455** [comment]
![image](https://user-images.githubusercontent.com/30395287/79159551-4b531280-7da6-11ea-93a4-eb2ad873689d.png)

Hardcoded coordinates to Hall Building to show that the feature works. (since we cannot go out):
![image](https://user-images.githubusercontent.com/30395287/79159626-6cb3fe80-7da6-11ea-897c-c36e3893602d.png)
