### ISSUE TITLE
US-7: Directions to destination

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#7]
As a user, I want to see directions on the map to reach from one campus building to another.

**Associated epic:** #18

**Tasks:**
- [x] Create the route from starting point to destination 
- [x] Display the route to the user on the map view 
- [ ] Provide step by step directions

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Enter starting point and destination and click go | Route is generated and displayed to the user on the map | 
2 | Begin navigation | Map is updated and shows the user directions | 

**Mockup:**
![image](https://user-images.githubusercontent.com/40539079/74111222-1554a080-4b61-11ea-8467-02839b6aa4c3.png)

**Note:** Could potentially be broken into multiple stories to support 
- Only outdoor map view
- Mix of outdoor and indoor map view

**Comment by david0455** [comment]
This user story has been duplicated and completed on issue #44
