### ISSUE TITLE
US-49: Adapt Updates From Software Architecture Design

### ISSUE THREAD

**Issue by a-paggabao** [samiha-rahman/soen390#77]
As a developper, I need to adapt the updates from the software architecture design, as well as refactor the file structure to apply Angular Style Standards.

**Tasks:**
- [x] Refactor physical file structure: names and location
- [x] Properly convert **Pages** to **Components**
- [x] Implement [ComponentFactoryResolver](https://angular.io/api/core/ComponentFactoryResolver) to replace the map builder pattern.
- [x] Update Unit Tests.
