### ISSUE TITLE
US-8: Different transportation ways to destination

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#8]
As a user, I want to have multiple transportation options (walk, public transportation, car, shuttle bus) to my destination. 
This includes the schedule for the Concordia Shuttle bus.

**Associated epic:** #18

**Tasks:**
- [x] Allow user to select their desired transportation method 
- [x] Accurately display directions based on desired transportation method
- [x] Support the Concordia Shuttle bus as a transportation option 
- [x] Add Concordia Shuttle bus schedule

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Select desired transportation method | Directions to destination are displayed following chosen transportation method | 
2 | Click on Concordia Shuttle bus schedule | Shuttle bus schedule should show accurate times in both directions | 

**Mockup:**
![image](https://user-images.githubusercontent.com/40539079/74111233-2bfaf780-4b61-11ea-949e-750d1359ff81.png)
