### ISSUE TITLE
US-51: Configure system tests

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/soen390#83]
As a developer, I need to have system tests working with the application in order to ensure quality using Protractor as the testing framework 

**Associated epic:** #35 

**Tasks:**
- [x] Protractor configuration file 
- [x] Typescript configuration file 
- [x] Base class to be used by other testing objects

**Comment by samiha-rahman** [comment]
Configuration complete, will create another developer story for additional tests
