### ISSUE TITLE
US-54: UI Navigation Search Bar

### ISSUE THREAD

**Issue by paulMoose** [samiha-rahman/soen390#88]
As a user, I would like to be able to input text to search from one location to another.

**Description:**
There should be an input box for the start location, end location and the mode of transportation. For the indoor maps, additional options should appear for the vertical mode of transportation (stairs, escalators, elevators). The search should provide suggestions since it is hard to type out a location by heart.
![image.png](https://images.zenhubusercontent.com/5e192e098dced90a7e0ee5a9/96f00568-f242-41cd-9d6e-d56b276057af)

** Tasks: **
- [x] Create the top bar component.
- [x] Cerating the search typeahead sugestions.
- [x] Update building config to include classes.
